name: electron-packager-hello-world
version: '0.1'
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
base: core18
confinement: strict
grade: stable

apps:
  electron-packager-hello-world:
    command: electron-quick-start/electron-quick-start --no-sandbox
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  electron-quick-start:
    plugin: python
    source: https://github.com/vmsreeram/oelp-microscope.git
    override-build: |
      npm config set scripts-prepend-node-path true
      npm install electron electron-packager --unsafe-perm=true
      npm install xhr2
      npm i mongodb
      npm i wifi-control
      npm i node-wifi
      npm i i
      npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
      cp -rv ./electron-quick-start-linux-* $SNAPCRAFT_PART_INSTALL/electron-quick-start
    
    build-snaps:
      - node/14/stable
    build-packages:
      - unzip
      - libc6-dev
    stage-packages:
      - libnss3
      - libnspr4
